### ISSUE TITLE
-1 lifetime parameter value in a mitigation request

### ISSUE THREAD

**Issue by rdanyliw** [dotswg/dots-signal-channel#5]
During slide 4 of Tiru Reddy's [signal/data channel presentation](https://datatracker.ietf.org/meeting/interim-2017-dots-03/materials/slides-interim-2017-dots-03-sessa-signal-and-data-channel/) at the  October 2017 interim, the [minutes](https://datatracker.ietf.org/meeting/interim-2017-dots-03/materials/minutes-interim-2017-dots-03-201710021000/) captured the need to clarify the use of "-1" as a lifetime parameter value in a mitigation request.

--[snip]--
Q: (Flemming Andreasen): What is the rational for the -1 value (for the lifetime parameter)?  Is this used instead of a heartbeat?
A: (Tiru Reddy): No, a heartbeat is still required
A: (Flemming Andreasen): What happens if a heartbeat is not received?
A: (Tiru Reddy): The mitigation continues
A: (Flemming Andreasen): This change seems significant as a soft state approach is no longer being taken.
A: (Tiru Reddy): It will be up to the server implementation.
A: (Flemming Andreasen): We need more discussion here.  Is it up to the server or indefinite?
A: (Mohamed Boucadair): This -1 value behavior is consistent with the requirements (SIG-006).
--[snip]--

**Comment by tireddy2** [comment]
The draft has been updated to clarify on use of -1 value, 
<snip>
The server MAY refuse indefinite
lifetime, for policy reasons; the granted lifetime value is
returned in the response.  DOTS clients MUST be prepared to not be
granted mitigations with indefinite lifetimes. 
</snip>
