### ISSUE TITLE
Use of .well-known URI

### ISSUE THREAD

**Issue by rdanyliw** [dotswg/dots-signal-channel#6]
During slide 14 of Tiru's [signal/data channel presentation](https://datatracker.ietf.org/meeting/interim-2017-dots-03/materials/slides-interim-2017-dots-03-sessa-signal-and-data-channel/) at the the October 2017 interim, the [minutes](https://datatracker.ietf.org/meeting/interim-2017-dots-03/materials/minutes-interim-2017-dots-03-201710021000/) captured discussion on relying on /.well-known/.

--[snip]--
Q: (Dave Dolson): Would the /.well-known/ be mandatory?
A: (Jon Shallow): Can we afford the overhead of discovery?
A: (Kaname Nishizuka): We use /.well-known/ in our NTT implementation.
A: (Dave Dolson): We might want the URI to be configurable to send different customers to different URIs
A: (Roman Danyliw): Let's mark this topic as an unresolved issue needing additional discussion, and track it in github
--[snip]--

**Comment by tireddy2** [comment]
This comment is addressed in 07 revision, uses well-known URI (e.g. /www.example.com/.wellknown/dots/v1/mitigate) and the URI suffix is dots
