### ISSUE TITLE
Default value for heartbeat-interval

### ISSUE THREAD

**Issue by rdanyliw** [dotswg/dots-signal-channel#7]
During slide 7 of Tiru's [signal/data channel presentation](https://datatracker.ietf.org/meeting/interim-2017-dots-03/materials/slides-interim-2017-dots-03-sessa-signal-and-data-channel/) at the the October 2017 interim, the [minutes](https://datatracker.ietf.org/meeting/interim-2017-dots-03/materials/minutes-interim-2017-dots-03-201710021000/) captured an unresolved discussion on the default value for the heartbeat-interval.

--[snip]--
Per Slide 7:
Q: (Flemming Andreasen): What's the rational for a heartbeat-interval = 91?  That value may be challenging for NATs
A: (Tiru Reddy): Timeout for NATS should be around 120s (per RFC4787)
A: (Flemming Andreasen): What's the basis for that value?  We have a requirements to run through a NAT
...
A: (Jon Shallow): The minimum for the heartbeat should be 10s
A: (Roman Danyliw): Let's mark this topic as an unresolved issue needing additional discussion, and track it in github
--[snip]--

**Comment by tireddy2** [comment]
This comment is addressed in 05 revision, default heartbeat-interval is changed to 30 seconds.
