### ISSUE TITLE
Default port value

### ISSUE THREAD

**Issue by rdanyliw** [dotswg/dots-signal-channel#8]
During slide 9 of Tiru's [signal/data channel presentation](https://datatracker.ietf.org/meeting/interim-2017-dots-03/materials/slides-interim-2017-dots-03-sessa-signal-and-data-channel/) at the the October 2017 interim, an unresolved issue on which port should be use as the default for signalling.  The [minutes](https://datatracker.ietf.org/meeting/interim-2017-dots-03/materials/minutes-interim-2017-dots-03-201710021000/) also captured the following:

--[snip]--
Comment: (Roman Danyliw as individual): I endorse requesting a new port for the DOTS signal channel.
A: (Jon Shallow): We're currently using the CoAP port like other applications
A: (Andrew Mortensen): A distinct port could help in a gateway scenario
A: (Flemming Andreasen): If the signal channel needs a distinct port, does the data channel?
A: (Roman Danyliw): Let's mark this topic as an unresolved issue needing additional discussion, and track it in github
--[snip]--

**Comment by tireddy2** [comment]
This comment is addressed in the 07 revision, the revised draft requests IANA to assign a new port for DOTS signal channel.
